config/routes.rb
Rails.application.routes.draw do
  root to: 'admin/home#index'
  namespace :admin do
    resources :users
    #resources :sessions, except: [:destroy]
    #get 'sessions/new'
    post 'sessions/create'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
  end











  #get 'sessions/new'
  #get 'sessions/create'
  #get 'sessions/destroy'

  #get 'users/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :user_name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  def index
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if(@user && @user.authenticate(params[:password]))
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:alert] = "Email or Password Invalid"
      redirect_to admin_login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to admin_login_path, notice: "Loged out"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @user = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  def show
    @user = User.find(params[:id])
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    #raise params.inspect
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path
    end
  end

  def user_params
    params.require(:user).permit(:user_name, :email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/home/index.html.erb
<%#= session[:user_id]%>
<%#= @current_user.id%>
<% if @current_user && @current_user.id == 1%>
  <h1>Welcome Admin Portal</h1>
<% else %>
  <h1>Welcome Admin Portal</h1>
  <%= link_to "Login", admin_login_path  %>
<% end %>

app/views/admin/users/_form.html.erb
<table>
  <tr>
    <td> User Name </td>
    <td> <%= f.text_field :user_name%></td>
  </tr>
  <%  @user.errors.full_messages_for(:user_name).each do |unameErr| %>
  <tr><td colspan="2"> <%= unameErr %></td></tr>
  <% end%>
  <tr>
    <td> Email </td>
    <td> <%= f.text_field :email%></td>
  </tr>
  <%  @user.errors.full_messages_for(:email).each do |emailErr| %>
  <tr><td colspan="2"> <%= emailErr %></td></tr>
  <% end%>
  <tr>
    <td> password </td>
    <td> <%= f.password_field :password%></td>
  </tr>
  <%  @user.errors.full_messages_for(:password).each do |pwErr| %>
  <tr><td colspan="2"> <%= pwErr %></td></tr>
  <% end%>
  <tr>
    <td> </td>
    <td> <%= f.submit "Submit"%></td>
  </tr>
</table>

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<%= form_for(@user, url: admin_user_path) do |f|%>
<%= render partial: "form", locals: {f: f}%>
<% end %>

app/views/admin/users/index.html.erb
<h1>Admin::Users</h1>
<%= link_to "Add New User", new_admin_user_path %>
<table>
  <tr>
    <td>UserName</td>
    <td>Email</td>
    <td>Status</td>
    <td>Action</td>
  </tr>
  <% if @user.empty? %>
    <tr><td colspan="4">No Users Found</td></tr>
  <% else %>
    <% @user.each do |user| %>
    <tr>
      <td> <%= user.user_name %></td>
      <td> <%= user.email %></td>
      <td>Status</td>
      <td>
        <%= link_to "Show", admin_user_path(user.id) %>
        <%= link_to "Edit", edit_admin_user_path(user.id) %>
        <%= link_to "Delete", admin_user_path(user.id), method: :delete,
                data: {confirm: "Are you sure you want to delete this user "+ user.user_name + "?"} %>
      </td>
    </tr>
    <% end %>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<h1>Admin::Users#index</h1>
<%= form_for(@user, url: admin_users_path) do |f|%>
<%= render partial: "form", locals: {f: f}%>
<% end %>

app/views/admin/users/show.html.erb
<h1>Admin User View</h1>
<table>
    <tr>
      <td> User Name: </td>
      <td> <%= @user.user_name %></td>
    </tr>
    <tr>
      <td> Email: </td>
      <td> <%= @user.email %></td>
    </tr>
</table>

app/views/layouts/_header.html.erb
<% if @current_user%>
  Loged in as <%= @current_user.email %>
  <%= link_to "Logout", admin_logout_path %>
  <% if @current_user.id == 1 %>
    <table>
      <tr>
      <td><%= link_to "Home", root_path %></td>
      <td><%= link_to "Users", admin_users_path %></td>
      <td><%= link_to "Categories" %></td>
      <td><%= link_to "Products" %></td>
      </tr>
    </table>
  <% else %>
    <%= link_to "Login" %>
    <%= link_to "Signup"%>
    <table>
      <tr>
      <td><%= link_to "Home" %></td>
      <td><%= link_to "Categories" %></td>
      <td><%= link_to "Products"%></td>
      </tr>
    </table>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>